/*
QMM2 - Q3 MultiMod 2
Copyright 2025
https://github.com/thecybermind/qmm2/
3-clause BSD license: https://opensource.org/license/bsd-3-clause

Created By:
	Kevin Masterson < k.m.masterson@gmail.com >

*/

#ifndef __QMM2_GAME_JK2SP_H__
#define __QMM2_GAME_JK2SP_H__

// import ("syscall") cmds
enum {
	G_PRINTF,
	G_WRITECAM,
	G_ERROR,
	G_MILLISECONDS,
	G_CVAR,
	G_CVAR_SET,
	G_CVAR_VARIABLE_INTEGER_VALUE,
	G_CVAR_VARIABLE_STRING_BUFFER,
	G_ARGC,
	G_ARGV,
	G_FS_FOPEN_FILE,
	G_FS_READ,
	G_FS_WRITE,
	G_FS_FCLOSE_FILE,
	G_FS_READFILE,
	G_FS_FREEFILE,
	G_FS_GETFILELIST,
	G_APPENDTOSAVEGAME,
	G_READFROMSAVEGAME,
	G_READFROMSAVEGAMEOPTIONAL,
	G_SEND_CONSOLE_COMMAND_EX,
	G_DROP_CLIENT,
	G_SEND_SERVER_COMMAND,
	G_SET_CONFIGSTRING,
	G_GET_CONFIGSTRING,
	G_GET_USERINFO,
	G_SET_USERINFO,
	G_GET_SERVERINFO,
	G_SET_BRUSH_MODEL,
	G_TRACE,
	G_POINT_CONTENTS,
	G_IN_PVS,
	G_IN_PVS_IGNOREPORTALS,
	G_ADJUSTAREAPORTALSTATE,
	G_AREAS_CONNECTED,
	G_LINKENTITY,
	G_UNLINKENTITY,
	G_ENTITIES_IN_BOX,
	G_ENTITY_CONTACT,
	GVP_VOICEVOLUME,
	G_MALLOC,
	G_FREE,
	G_G2API_PRECACHEGHOUL2MODEL,
	G_G2API_INITGHOUL2MODEL,
	G_G2API_SETLODBIAS,
	G_G2API_SETSKIN,
	G_G2API_SETSHADER,
	G_G2API_REMOVEGHOUL2MODEL,
	G_G2API_SETSURFACEONOFF,
	G_G2API_SETROOTSURFACE,
	G_G2API_REMOVESURFACE,
	G_G2API_ADDSURFACE,
	G_G2API_SETBONEANIM,
	G_G2API_GETBONEANIM,
	G_G2API_GETBONEANIMINDEX,
	G_G2API_GETANIMRANGE,
	G_G2API_GETANIMRANGEINDEX,
	G_G2API_PAUSEBONEANIM,
	G_G2API_PAUSEBONEANIMINDEX,
	G_G2API_ISPAUSED,
	G_G2API_STOPBONEANIM,
	G_G2API_SETBONEANGLES,
	G_G2API_SETBONEANGLESMATRIX,
	G_G2API_STOPBONEANGLES,
	G_G2API_REMOVEBONE,
	G_G2API_REMOVEBOLT,
	G_G2API_ADDBOLT,
	G_G2API_ADDBOLTSURFNUM,
	G_G2API_ATTACHG2MODEL,
	G_G2API_DETACHG2MODEL,
	G_G2API_ATTACHENT,
	G_G2API_DETACHENT,
	G_G2API_GETBOLTMATRIX,
	G_G2API_LISTSURFACES,
	G_G2API_LISTBONES,
	G_G2API_HAVEWEGHOUL2MODELS,
	G_G2API_SETGHOUL2MODELFLAGS,
	G_G2API_GETGHOUL2MODELFLAGS,
	G_G2API_GETANIMFILENAME,
	G_G2API_COLLISIONDETECT,
	G_G2API_GIVEMEVECTORFROMMATRIX,
	G_G2API_COPYGHOUL2INSTANCE,
	G_G2API_CLEANGHOUL2MODELS,
	G_THEGHOUL2INFOARRAY,
	G_G2API_GETPARENTSURFACE,
	G_G2API_GETSURFACEINDEX,
	G_G2API_GETSURFACENAME,
	G_G2API_GETGLANAME,
	G_G2API_SETNEWORIGIN,
	G_G2API_GETBONEINDEX,
	G_G2API_STOPBONEANGLESINDEX,
	G_G2API_STOPBONEANIMINDEX,
	G_G2API_SETBONEANGLESINDEX,
	G_G2API_SETBONEANGLESMATRIXINDEX,
	G_G2API_SETBONEANIMINDEX,
	G_G2API_SAVEGHOUL2MODELS,
	G_G2API_LOADGHOUL2MODELS,
	G_G2API_LOADSAVECODEDESTRUCTGHOUL2INFO,
	G_G2API_FREESAVEBUFFER,
	G_G2API_GETANIMFILENAMEINDEX,
	G_G2API_GETSURFACERENDERSTATUS,
	G_RE_REGISTERSKIN,
	G_RE_GETANIMATIONCFG,

	G_PRINT = G_PRINTF,
};

// export ("vmMain") cmds
enum {
	GAMEV_APIVERSION,
	GAME_INIT,
	GAME_SHUTDOWN,
	GAME_WRITE_LEVEL,
	GAME_READ_LEVEL,
	GAME_GAMEALLOWEDTOSAVEHERE,
	GAME_CLIENT_CONNECT,
	GAME_CLIENT_BEGIN,
	GAME_CLIENT_USERINFO_CHANGED,
	GAME_CLIENT_DISCONNECT,
	GAME_CLIENT_COMMAND,
	GAME_CLIENT_THINK,
	GAME_RUN_FRAME,
	GAME_CONSOLE_COMMAND,
	GAME_PRINTENTCLASSNAME,
	GAME_VALIDATEANIMRANGE,
	GAMEVP_GENTITIES,
	GAMEV_GENTITYSIZE,
	GAMEV_NUM_ENTITIES,

	GAME_SPAWN_ENTITIES = GAME_INIT,
};

// these import messages do not have an exact analogue in JK2SP
enum {
	G_CVAR_REGISTER = -100,			// void (vmcvar_t* ignored_cvar, const char *varName, const char *defaultValue, int flags)
	G_SEND_CONSOLE_COMMAND,			// void (int ignored_exec_when, const char *text)
	// helper for plugins to not need separate logic
	G_LOCATE_GAME_DATA,				// void (gentity_t *gEnts, int numGEntities, int sizeofGEntity_t, playerState_t *clients, int sizeofGameClient)
	G_GET_ENTITY_TOKEN,				// qboolean (char *buffer, int bufferSize)
};

#endif // __QMM2_GAME_JK2SP_H__
