/*
QMM2 - Q3 MultiMod 2
Copyright 2025
https://github.com/thecybermind/qmm2/
3-clause BSD license: https://opensource.org/license/bsd-3-clause

Created By:
	Kevin Masterson < cybermind@gmail.com >

*/

#ifndef __QMM2_GAME_QUAKE2_H__
#define __QMM2_GAME_QUAKE2_H__

// import ("syscall") cmds
enum {
	G_BPRINTF,
	G_DPRINTF,
	G_CPRINTF,
	G_CENTERPRINTF,
	G_SOUND,
	G_POSITIONED_SOUND,
	G_CONFIGSTRING,
	G_ERROR,
	G_MODELINDEX,
	G_SOUNDINDEX,
	G_IMAGEINDEX,
	G_SETMODEL,
	G_TRACE,
	G_POINTCONTENTS,
	G_INPVS,
	G_INPHS,
	G_SETAREAPORTALSTATE,
	G_AREASCONNECTED,
	G_LINKENTITY,
	G_UNLINKENTITY,
	G_BOXEDICTS,
	G_PMOVE,
	G_MULTICAST,
	G_UNICAST,
	G_MSG_WRITECHAR,
	G_MSG_WRITEBYTE,
	G_MSG_WRITESHORT,
	G_MSG_WRITELONG,
	G_MSG_WRITEFLOAT,
	G_MSG_WRITESTRING,
	G_MSG_WRITEPOSITION,
	G_MSG_WRITEDIR,
	G_MSG_WRITEANGLE,
	G_TAGMALLOC,
	G_TAGFREE,
	G_FREETAGS,
	G_CVAR,
	G_CVAR_SET,
	G_CVAR_FORCESET,
	G_ARGC,
	G_ARGV,
	G_ARGS,
	G_ADDCOMMANDSTRING,
	G_DEBUGGRAPH,

	G_PRINT = G_BPRINTF,
	G_SET_CONFIGSTRING = G_CONFIGSTRING,
	G_SEND_CONSOLE_COMMAND = G_ADDCOMMANDSTRING,
};

// export ("vmMain") cmds
enum {
	GAMEV_APIVERSION,
	GAME_INIT,
	GAME_SHUTDOWN,
	GAME_SPAWN_ENTITIES,
	GAME_WRITE_GAME,
	GAME_READ_GAME,
	GAME_WRITE_LEVEL,
	GAME_READ_LEVEL,
	GAME_CLIENT_CONNECT,
	GAME_CLIENT_BEGIN,
	GAME_CLIENT_USERINFO_CHANGED,
	GAME_CLIENT_DISCONNECT,
	GAME_CLIENT_COMMAND,
	GAME_CLIENT_THINK,
	GAME_RUN_FRAME,
	GAME_SERVER_COMMAND,
	GAMEVP_EDICTS,
	GAMEV_EDICT_SIZE,
	GAMEV_NUM_EDICTS,
	GAMEV_MAX_EDICTS,

	GAME_CONSOLE_COMMAND = GAME_SERVER_COMMAND,
};

// these import messages do not have an exact analogue in MOHAA
enum {
	G_CVAR_REGISTER = -100,
	G_CVAR_VARIABLE_STRING_BUFFER,
	G_CVAR_VARIABLE_INTEGER_VALUE,
	G_FS_FOPEN_FILE,
	G_FS_READ,
	G_FS_WRITE,
	G_FS_FCLOSE_FILE,
};

// other values
enum {
	EXEC_APPEND,
	FS_READ,
	CVAR_ROM = CVAR_NOSET,
};

#endif // __QMM2_GAME_QUAKE2_H__
